Repository ArezkiBe/Vers_git, pull requests merged in 2024-02, with the labels that each got.

#1 Creation de deux nouvelles Issue Templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: enhancement

#3 Ajout de pull request template
  .github/pull_request_template.md
Labels: documentation

#6 Completion de la deuxieme feature
  deuxieme_feature.txt
Labels: enhancement

#11 Completion de la troisieme feature
  troisieme_feature.txt
Labels: enhancement

#16 Completion de la quatrieme feature
  quatrieme_feature.txt
Labels: enhancement

#20 Completion de la cinquieme feature
  cinquieme_feature.txt
Labels: enhancement

#22 Completion de la sixieme feature
  sixieme_feature.txt
Labels: enhancement

#24 Completion de la septieme feature
  septieme_feature.txt
Labels: enhancement

#26 Completion de la huitieme feature
  huitieme feature.txt
Labels: enhancement

#27 Completion du premier bug
  premiere_feature.txt
Labels: enhancement

#28 Completion du deuxieme bug
  deuxieme_feature.txt
Labels: bug

#29 Completion du troisieme bug
  troisieme_feature.txt
Labels: bug

#30 Completion du quatrieme bug
  quatrieme_feature.txt
Labels: bug

#31 Completion du cinquieme bug
  cinquieme_feature.txt
Labels: bug

#32 Completion
  sixieme_feature.txt
Labels: bug

#33 Septième bug
  septieme_feature.txt
Labels: bug

#34 Huitième bug
  huitieme feature.txt
Labels: bug

#37 Update README.md
  README.md
Labels: documentation

#38 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
